function __persist_session_ids
    command -q persist; or return
    persist ls 2>/dev/null | awk 'NR > 1 && $1 ~ /^[0-9]+$/ {print $1}'
end

complete -c persist -n '__fish_use_subcommand' -s h -l help -d 'Show help'
complete -c persist -n '__fish_use_subcommand' -s V -l version -d 'Show version'
complete -c persist -n '__fish_use_subcommand' -a help -d 'Show help'
complete -c persist -n '__fish_use_subcommand' -a version -d 'Show version'
complete -c persist -n '__fish_use_subcommand' -a doctor -d 'Diagnose local setup'
complete -c persist -n '__fish_use_subcommand' -a config -d 'Show configuration'
complete -c persist -n '__fish_use_subcommand' -a daemon -d 'Manage daemon'
complete -c persist -n '__fish_use_subcommand' -a new -d 'Create session'
complete -c persist -n '__fish_use_subcommand' -a ls -d 'List sessions'
complete -c persist -n '__fish_use_subcommand' -a ps -d 'Show process tree'
complete -c persist -n '__fish_use_subcommand' -a stats -d 'Show process counters'
complete -c persist -n '__fish_use_subcommand' -a snapshot -d 'Show snapshot'
complete -c persist -n '__fish_use_subcommand' -a metrics -d 'Show metrics'
complete -c persist -n '__fish_use_subcommand' -a attach -d 'Attach session'
complete -c persist -n '__fish_use_subcommand' -a close -d 'Close session'
complete -c persist -n '__fish_use_subcommand' -a kill -d 'Terminate session'
complete -c persist -n '__fish_use_subcommand' -a log -d 'Read session log'
complete -c persist -n '__fish_use_subcommand' -a rename -d 'Rename session'
complete -c persist -n '__fish_use_subcommand' -a detach -d 'Detach client'
complete -c persist -n '__fish_use_subcommand' -a note -d 'Manage note'
complete -c persist -n '__fish_use_subcommand' -a tag -d 'Manage tags'
complete -c persist -n '__fish_use_subcommand' -a pin -d 'Pin session'
complete -c persist -n '__fish_use_subcommand' -a unpin -d 'Unpin session'
complete -c persist -n '__fish_use_subcommand' -a lock -d 'Lock session'
complete -c persist -n '__fish_use_subcommand' -a unlock -d 'Unlock session'
complete -c persist -n '__fish_use_subcommand' -a replay -d 'Replay output'
complete -c persist -n '__fish_use_subcommand' -a install -d 'Install SSH hook'
complete -c persist -n '__fish_use_subcommand' -a uninstall -d 'Remove SSH hook'

complete -c persist -n '__fish_seen_subcommand_from config' -a show -d 'Show configuration'
complete -c persist -n '__fish_seen_subcommand_from daemon' -a 'start stop status'
complete -c persist -n '__fish_seen_subcommand_from ls' -s t -l tag -r -d 'Filter by tag'
complete -c persist -n '__fish_seen_subcommand_from attach' -s r -l readonly -d 'Readonly attach'
complete -c persist -n '__fish_seen_subcommand_from attach' -a '(__persist_session_ids)'

complete -c persist -n '__fish_seen_subcommand_from ps stats snapshot close kill detach pin unpin lock unlock' -a '(__persist_session_ids)'
complete -c persist -n '__fish_seen_subcommand_from rename note' -a '(__persist_session_ids)'
complete -c persist -n '__fish_seen_subcommand_from tag' -a '(__persist_session_ids)'
complete -c persist -n '__fish_seen_subcommand_from tag' -a 'add remove list'

complete -c persist -n '__fish_seen_subcommand_from log' -a '(__persist_session_ids) export search'
complete -c persist -n '__fish_seen_subcommand_from export' -a '(__persist_session_ids)'
complete -c persist -n '__fish_seen_subcommand_from export' -s o -l output -r -d 'Output file'
complete -c persist -n '__fish_seen_subcommand_from search' -s s -l session -r -a '(__persist_session_ids)' -d 'Session ID'
complete -c persist -n '__fish_seen_subcommand_from search' -s i -l ignore-case -d 'Ignore case'

complete -c persist -n '__fish_seen_subcommand_from replay' -a '(__persist_session_ids)'
complete -c persist -n '__fish_seen_subcommand_from replay' -s t -l tail -r -d 'Last lines'
complete -c persist -n '__fish_seen_subcommand_from replay' -s h -l head -r -d 'First lines'
complete -c persist -n '__fish_seen_subcommand_from replay' -s s -l speed -r -d 'Replay factor'
complete -c persist -n '__fish_seen_subcommand_from replay' -s f -l follow -d 'Follow output'
complete -c persist -n '__fish_seen_subcommand_from uninstall' -l purge -d 'Remove all data'
